version: '3'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    links:
      - express
      - grafana
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email ${CERTBOT_EMAIL} -d ${CERTBOT_DOMAIN} -d ${CERTBOT_DOMAIN2} --agree-tos --renew-by-default
  
  express:
    build: ./express
    container_name: express
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/config
      - prometheus_data:/prometheus
    command:
      - "--config.file=/config/prometheus.yml"
    networks:
      - monitoring-analytics
      - default

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    links:
      - prometheus
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_DOMAIN=evyn.me
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=${SMTP_HOST}
      - GF_SMTP_USER=${SMTP_USER}
      - GF_SMTP_PASSWORD=${SMTP_PASSWORD}
      - GF_SMTP_SKIP_VERIFY=false
      - GF_SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - GF_SMTP_FROM_NAME=${SMTP_FROM_NAME}
  
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    restart: unless-stopped
    volumes:
      - ./uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  monitoring-analytics:
    name: monitoring-analytics
